Algoritmo "Entrada e saida de dados"
// Descrição   : Entrada e saida de dados
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/03/2022
Var
// Seção de Declarações das variáveis 
     nome: caractere
     nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("pau no cu")
     leia(nome)
     escreval("sua idade parceiro")
     leia(nota)
     
     escreval("nome digitadado foi:", nome)
     escreval("tu é mó mongol:", nota)
     
Fimalgoritmo